#!/usr/bin/env python3
"""
SSH 配置管理器 - 负责 SSH config 文件的读写操作
"""

import os
import re
from pathlib import Path


class SSHConfigManager:
    """SSH config 文件管理器"""

    def __init__(self, config_file: Path):
        self.config_file = config_file

    @staticmethod
    def _atomic_write(path: Path, content: str) -> None:
        """原子写入 config（临时文件 + os.replace），避免崩溃/断电损坏 config。

        与 StateManager 保持一致：先写同目录唯一临时文件，再 os.replace 原子替换。
        """
        tmp = path.with_name(f"{path.name}.{os.getpid()}.tmp")
        try:
            tmp.write_text(content, encoding="utf-8")
            os.replace(tmp, path)
        finally:
            try:
                if tmp.exists():
                    tmp.unlink()
            except OSError:
                pass

    def update_host(self, label: str, host: str, key_file: Path):
        """更新或添加 Host 配置（忽略大小写，把同名块的所有大小写变体合并为单块）"""
        config_block = self._generate_config_block(label, host, key_file)

        if not self.config_file.exists():
            self._atomic_write(self.config_file, config_block)
            return

        content = self.config_file.read_text(encoding="utf-8")

        # 查找所有同名（忽略大小写）的配置块，合并为单个新块
        pattern = rf"^# {re.escape(label)} - Auto-generated.*?(?=^#|\Z)"
        flags = re.MULTILINE | re.DOTALL | re.IGNORECASE
        matches = list(re.finditer(pattern, content, flags))
        if matches:
            insert_pos = matches[0].start()
            for m in reversed(matches):
                content = content[: m.start()] + content[m.end() :]
            content = content[:insert_pos] + config_block.rstrip() + "\n\n" + content[insert_pos:]
        else:
            content += "\n" + config_block

        # 规整连续空行
        content = re.sub(r"\n{3,}", "\n\n", content)
        self._atomic_write(self.config_file, content)

    def remove_host(self, label: str):
        """从 SSH config 中删除指定标签的配置（忽略大小写）"""
        if not self.config_file.exists():
            return

        content = self.config_file.read_text(encoding="utf-8")
        pattern = rf"^# {re.escape(label)} - Auto-generated.*?(?=^#|\Z)"
        content = re.sub(pattern, "", content, flags=re.MULTILINE | re.DOTALL | re.IGNORECASE)
        # 规整连续空行
        content = re.sub(r"\n{3,}", "\n\n", content)
        self._atomic_write(self.config_file, content)

    def has_host(self, label: str) -> bool:
        """检查 SSH config 中是否存在指定 Host（忽略大小写）"""
        if not self.config_file.exists():
            return False
        try:
            content = self.config_file.read_text(encoding="utf-8")
            pattern = rf"^Host {re.escape(label)}\s*$"
            return re.search(pattern, content, re.MULTILINE | re.IGNORECASE) is not None
        except OSError:
            return False

    def get_hostname(self, host: str) -> str | None:
        """从 SSH config 反查指定 Host 对应的真实 HostName

        用于把别名还原为真实主机名（SSH 实际连接的目标）。
        找不到该 Host 块或其无 HostName 时返回 None。
        """
        if not self.config_file.exists():
            return None
        try:
            content = self.config_file.read_text(encoding="utf-8")
        except OSError:
            return None

        # 定位 Host 块（忽略大小写），匹配到下一个 Host/文件结尾为止
        lines = content.splitlines()
        in_block = False
        for line in lines:
            stripped = line.strip()
            if stripped.lower().startswith("host "):
                # 是新的 Host 块开头
                parts = stripped[5:].strip().split()
                if not in_block:
                    # 记录当前 Host 名
                    if parts and parts[0].lower() == host.lower():
                        in_block = True
                    continue
                else:
                    # 上一个块已结束，没找到 HostName
                    return None
            if in_block and stripped.lower().startswith("hostname"):
                hostname_val = stripped[8:].strip()
                return hostname_val if hostname_val else None
        return None

    @staticmethod
    def _generate_config_block(label: str, host: str, key_file: Path) -> str:
        """生成 SSH config 配置块"""
        # 转换为 POSIX 路径格式（SSH config 标准）。
        # 注意：仅靠 Path.as_posix() 在 Linux 上不会把 Windows 反斜杠转成斜杠
        # （Linux 下反斜杠是普通字符），故统一用 replace 强制转换，跨平台一致。
        key_file_str = str(key_file).replace("\\", "/")

        return f"""# {label} - Auto-generated by sshm
Host {label}
  HostName {host}
  User git
  IdentityFile {key_file_str}
  IdentitiesOnly yes

"""
