"""SSHConfigManager 单元测试：Host 块增删改查与原子写入"""

from pathlib import Path

import pytest


@pytest.fixture
def config_file(tmp_path: Path) -> Path:
    return tmp_path / "config"


@pytest.fixture
def cfg(config_file: Path):
    from sshm.core.services.ssh.config import SSHConfigManager

    return SSHConfigManager(config_file)


class TestUpdateHost:
    def test_create_new_config(self, cfg, config_file):
        """config 不存在时，新建文件并写入 Host 块"""
        cfg.update_host("work", "gitlab.com", Path("/tmp/id_ed25519.work"))
        assert config_file.exists()
        content = config_file.read_text(encoding="utf-8")
        assert "# work - Auto-generated by sshm" in content
        assert "Host work" in content
        assert "HostName gitlab.com" in content
        assert "IdentityFile /tmp/id_ed25519.work" in content

    def test_update_same_host_replaces(self, cfg, config_file):
        """重复 update 同名 Host 时替换而非追加（合并为单块）"""
        cfg.update_host("work", "gitlab.com", Path("/tmp/k1"))
        cfg.update_host("work", "new.host.com", Path("/tmp/k2"))
        content = config_file.read_text(encoding="utf-8")
        assert content.count("Host work") == 1
        assert "HostName new.host.com" in content
        assert "HostName gitlab.com" not in content

    def test_update_two_hosts_both_kept(self, cfg, config_file):
        """不同标签的 Host 块并存"""
        cfg.update_host("work", "gitlab.com", Path("/tmp/k1"))
        cfg.update_host("personal", "github.com", Path("/tmp/k2"))
        content = config_file.read_text(encoding="utf-8")
        assert content.count("Host work") == 1
        assert content.count("Host personal") == 1

    def test_after_update_has_host_true(self, cfg):
        cfg.update_host("work", "gitlab.com", Path("/tmp/k1"))
        assert cfg.has_host("work") is True
        assert cfg.has_host("missing") is False


class TestRemoveHost:
    def test_remove_existing(self, cfg, config_file):
        cfg.update_host("work", "gitlab.com", Path("/tmp/k1"))
        cfg.remove_host("work")
        assert "Host work" not in config_file.read_text(encoding="utf-8")

    def test_remove_missing_is_noop(self, cfg):
        # 移除不存在的 Host 不应报错，也不应创建文件
        cfg.remove_host("nope")
        # 文件此时不存在（remove_host 对不存在文件直接 return）

    def test_remove_one_keeps_other(self, cfg, config_file):
        cfg.update_host("work", "gitlab.com", Path("/tmp/k1"))
        cfg.update_host("personal", "github.com", Path("/tmp/k2"))
        cfg.remove_host("work")
        content = config_file.read_text(encoding="utf-8")
        assert "Host work" not in content
        assert "Host personal" in content


class TestHasHost:
    def test_false_when_no_file(self, cfg):
        assert cfg.has_host("anything") is False


class TestGetHostname:
    def test_no_file_returns_none(self, cfg):
        assert cfg.get_hostname("work") is None

    def test_returns_hostname(self, cfg):
        cfg.update_host("work", "gitlab.com", Path("/tmp/k1"))
        assert cfg.get_hostname("work") == "gitlab.com"

    def test_case_insensitive_match(self, cfg):
        cfg.update_host("work", "gitlab.com", Path("/tmp/k1"))
        assert cfg.get_hostname("WORK") == "gitlab.com"

    def test_returns_none_for_missing(self, cfg):
        cfg.update_host("work", "gitlab.com", Path("/tmp/k1"))
        assert cfg.get_hostname("other") is None


class TestGenerateConfigBlock:
    def test_windows_path_converted_to_posix(self):
        from sshm.core.services.ssh.config import SSHConfigManager

        block = SSHConfigManager._generate_config_block("work", "gitlab.com", Path("C:\\Users\\x\\id_ed25519.work"))
        assert "IdentityFile C:/Users/x/id_ed25519.work" in block
        assert "\\" not in block.split("IdentityFile")[-1]


class TestAtomicWrite:
    def test_no_tmp_leftover(self, cfg, config_file):
        """原子写入后不应残留临时文件"""
        cfg.update_host("work", "gitlab.com", Path("/tmp/k1"))
        assert not list(config_file.parent.glob("config.*.tmp"))
        assert config_file.exists()
