#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SSH 配置管理器 - 负责 SSH config 文件的读写操作
"""

import re
from pathlib import Path


class SSHConfigManager:
    """SSH config 文件管理器"""
    
    def __init__(self, config_file: Path):
        self.config_file = config_file
    
    def update_host(self, label: str, host: str, key_file: Path):
        """更新或添加 Host 配置"""
        config_block = self._generate_config_block(label, host, key_file)
        
        if not self.config_file.exists():
            self.config_file.write_text(config_block, encoding='utf-8')
            return
        
        content = self.config_file.read_text(encoding='utf-8')
        
        # 查找并替换已存在的配置块
        pattern = rf'^# {re.escape(label)} - Auto-generated.*?(?=^#|\Z)'
        if re.search(pattern, content, re.MULTILINE | re.DOTALL):
            content = re.sub(pattern, config_block.rstrip() + '\n\n', 
                           content, flags=re.MULTILINE | re.DOTALL)
        else:
            content += '\n' + config_block
        
        self.config_file.write_text(content, encoding='utf-8')
    
    def remove_host(self, label: str):
        """从 SSH config 中删除指定标签的配置"""
        if not self.config_file.exists():
            return
        
        content = self.config_file.read_text(encoding='utf-8')
        pattern = rf'^# {re.escape(label)} - Auto-generated.*?(?=^#|\Z)'
        content = re.sub(pattern, '', content, flags=re.MULTILINE | re.DOTALL)
        self.config_file.write_text(content, encoding='utf-8')
    
    def rename_host(self, old_label: str, new_label: str):
        """重命名 SSH config 中的 Host"""
        if not self.config_file.exists():
            return
        
        content = self.config_file.read_text(encoding='utf-8')
        pattern = rf'^# {re.escape(old_label)} - Auto-generated.*?(?=^#|\Z)'
        match = re.search(pattern, content, re.MULTILINE | re.DOTALL)
        
        if match:
            old_block = match.group(0)
            new_block = old_block.replace(f"# {old_label} - ", f"# {new_label} - ")
            new_block = re.sub(rf'^Host {re.escape(old_label)}$', 
                             f'Host {new_label}', new_block, flags=re.MULTILINE)
            content = content.replace(old_block, new_block)
            self.config_file.write_text(content, encoding='utf-8')
    
    @staticmethod
    def _generate_config_block(label: str, host: str, key_file: Path) -> str:
        """生成 SSH config 配置块"""
        # 转换为 POSIX 路径格式（SSH config 标准）
        if hasattr(key_file, 'as_posix'):
            key_file_str = key_file.as_posix()
        else:
            key_file_str = str(key_file).replace('\\', '/')
        
        return f"""# {label} - Auto-generated by sshm
Host {label}
  HostName {host}
  User git
  IdentityFile {key_file_str}
  IdentitiesOnly yes

"""
